name: CI con gradle

on:
  push:
    branches: [ master ] #se ejecutará cuando hagamos un push a esta rama
  workflow_dispatch: #tambien podremos ejecutar el workflow manualmente desde github

jobs:
  build:
    runs-on: ubuntu-latest #trabjaremos sobre una maquina ubuntu
    permissions: 
      contents: read #el repo solo se puede leer
      packages: write #para tener acceso a os binarios resultantes de los build

    steps:
        #### CONFIGURACION DEL ENTORNO: jdk8 y gradle 2.1 ####
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace }}
      - name: set up gradle 
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 2.1
          
       #### BUILDS ####
      - name: hacer build del frontend
        working-directory: src/Clients
        run: ./gradlew build
      
      - name: hacer build del backend
        working-directory: src/Backend/OrderService
        run: ./gradlew build test
      
      - name: dockerizar el front y el backend
        run: |
          cp src/Clients/build/libs/*.war deploy/docker/Clients/drop 
          docker build -t practica2_gps/web deploy/docker/Clients
          cp src/Backend/OrderService/build/libs/ordering* deploy/docker/Order/drop
          docker build -t practica2_gps/order deploy/docker/Order 
          
        ##SUBIR IMAGENES A DOCKERHUB ##
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Etiquetar con formato DockerHub
        run: | 
          docker tag practica2_gps/web ${{ secrets.DOCKERHUB_USERNAME }}/practica2_gps:web
          docker tag practica2_gps/order ${{ secrets.DOCKERHUB_USERNAME }}/practica2_gps:order
      - name: Push a DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/practica2_gps:order
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/practica2_gps:web
          


          
        

